import { Directory, Filesystem } from '@capacitor/filesystem'
import { Share } from '@capacitor/share'
import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { SettlementResult, Transaction } from '../types'
import { formatRupees } from './settlement'

export async function generateAndSharePDF(
  tx: Transaction,
  result: SettlementResult,
  action: 'share' | 'download',
) {
  const doc = new jsPDF()

  // Title
  doc.setFontSize(20)
  doc.text(`Hisab Clear: ${tx.name}`, 14, 22)

  // Meta
  doc.setFontSize(12)
  doc.setTextColor(100)
  doc.text(`Total pool: ${formatRupees(result.total)}`, 14, 32)
  doc.text(`Details: ${result.sharePerPersonNote}`, 14, 40)

  // Balances table
  doc.setFontSize(14)
  doc.setTextColor(0)
  doc.text('Paid vs fair share', 14, 52)

  const tableData = result.balances.map((b) => {
    let diff = '0'
    if (b.balance > 0) diff = `+${formatRupees(b.balance)}`
    else if (b.balance < 0) diff = formatRupees(b.balance)
    
    return [
      b.note ? `${b.name} (${b.note})` : b.name,
      formatRupees(b.paid),
      formatRupees(b.share),
      diff,
    ]
  })

  autoTable(doc, {
    startY: 56,
    head: [['Person', 'Paid', 'Share', '+ / -']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: [42, 157, 143] },
  })

  // Transfers
  const finalY = (doc as any).lastAutoTable.finalY || 60
  
  doc.setFontSize(14)
  doc.setTextColor(0)
  doc.text('Suggested transfers', 14, finalY + 12)

  if (result.transfers.length === 0) {
    doc.setFontSize(12)
    doc.setTextColor(100)
    doc.text('Everyone is already square.', 14, finalY + 22)
  } else {
    doc.setFontSize(12)
    let yPos = finalY + 22
    result.transfers.forEach((t) => {
      doc.text(`${t.fromName}  ->  ${t.toName}  :  ${formatRupees(t.amount)}`, 14, yPos)
      yPos += 8
    })
  }

  // Footer
  doc.setFontSize(10)
  doc.setTextColor(150)
  doc.text('Generated by Hisab Clear', 14, doc.internal.pageSize.getHeight() - 10)

  const fileName = `HisabClear_${tx.name.replace(/[^a-zA-Z0-9]/g, '_')}.pdf`

  try {
    const pdfDataUri = doc.output('datauristring')
    const base64Data = pdfDataUri.split(',')[1]

    if (action === 'download') {
      try {
        await Filesystem.writeFile({
          path: fileName,
          data: base64Data,
          directory: Directory.Documents,
        })
        window.alert('PDF saved to Documents folder!')
      } catch (err) {
        // Fallback for web or if permissions fail
        doc.save(fileName)
      }
    } else {
      // share
      try {
        const savedFile = await Filesystem.writeFile({
          path: fileName,
          data: base64Data,
          directory: Directory.Cache,
        })
        await Share.share({
          title: `Hisab Clear: ${tx.name}`,
          text: `Here is the settlement summary for ${tx.name}`,
          url: savedFile.uri,
          dialogTitle: 'Share PDF Summary',
        })
      } catch (e) {
        window.alert('Sharing is not supported on this device/browser.')
      }
    }
  } catch (error) {
    console.error('PDF error', error)
    if (action === 'download') doc.save(fileName)
  }
}
