import { Directory, Filesystem } from '@capacitor/filesystem'
import { Share } from '@capacitor/share'
import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { SettlementResult, Transaction } from '../types'
import { formatRupees } from './settlement'

function cleanForPDF(str: string): string {
  return str
    .replace(/₹/g, 'Rs. ')
    .replace(/–/g, '-') // Replace en-dash with standard hyphen
    .replace(/[\u202F\u00A0]/g, '') // Remove narrow no-break space or non-breaking space (keeps numbers together)
}

export async function generateAndSharePDF(
  tx: Transaction,
  result: SettlementResult,
  action: 'share' | 'download',
): Promise<boolean | void> {
  const doc = new jsPDF()

  // Title
  doc.setFontSize(20)
  doc.text(`Hisab Clear: ${tx.name}`, 14, 22)

  // Meta
  doc.setFontSize(12)
  doc.setTextColor(100)
  doc.text(`Total expense: ${cleanForPDF(formatRupees(result.total))}`, 14, 32)
  doc.text(`Details: ${cleanForPDF(result.sharePerPersonNote)}`, 14, 40)

  // Balances table
  doc.setFontSize(14)
  doc.setTextColor(0)
  doc.text('Paid vs fair share', 14, 52)

  const tableData = result.balances.map((b) => {
    let diff = '0'
    let diffColor: [number, number, number] | undefined = undefined

    if (b.balance > 0) {
      diff = `+${cleanForPDF(formatRupees(b.balance))}`
      diffColor = [0, 120, 0] // Dark Green
    } else if (b.balance < 0) {
      diff = cleanForPDF(formatRupees(b.balance))
      diffColor = [180, 0, 0] // Dark Red
    }
    
    return [
      b.note ? `${b.name} (${b.note})` : b.name,
      cleanForPDF(formatRupees(b.paid)),
      cleanForPDF(formatRupees(b.share)),
      diffColor ? ({ content: diff, styles: { textColor: diffColor, fontStyle: 'bold' } } as any) : diff,
    ]
  })

  autoTable(doc, {
    startY: 56,
    head: [['Person', 'Paid', 'Share', '+ / -']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: [42, 157, 143] },
  })

  // Transfers
  const finalY = (doc as any).lastAutoTable.finalY || 60
  
  doc.setFontSize(14)
  doc.setTextColor(0)
  doc.text('Suggested transfers', 14, finalY + 12)

  if (result.transfers.length === 0) {
    doc.setFontSize(12)
    doc.setTextColor(100)
    doc.text('Everyone is already square.', 14, finalY + 22)
  } else {
    doc.setFontSize(12)
    let yPos = finalY + 22
    result.transfers.forEach((t) => {
      doc.text(`${t.fromName} -> ${t.toName} : ${cleanForPDF(formatRupees(t.amount))}`, 14, yPos)
      yPos += 8
    })
  }

  // Footer
  doc.setFontSize(10)
  doc.setTextColor(150)
  doc.text('Generated by Hisab Clear', 14, doc.internal.pageSize.getHeight() - 10)

  const fileName = `HisabClear_${tx.name.replace(/[^a-zA-Z0-9]/g, '_')}.pdf`

  try {
    const pdfDataUri = doc.output('datauristring')
    const base64Data = pdfDataUri.split(',')[1]

    if (action === 'download') {
      try {
        await Filesystem.writeFile({
          path: fileName,
          data: base64Data,
          directory: Directory.Documents,
        })
        return true
      } catch (err) {
        // Fallback for web or if permissions fail
        doc.save(fileName)
        return true
      }
    } else {
      // share
      try {
        const savedFile = await Filesystem.writeFile({
          path: fileName,
          data: base64Data,
          directory: Directory.Cache,
        })
        await Share.share({
          title: `Hisab Clear: ${tx.name}`,
          text: `Here is the settlement summary for ${tx.name}`,
          files: [savedFile.uri],
          dialogTitle: 'Share PDF Summary',
        })
      } catch (e: any) {
        if (e?.message?.toLowerCase().includes('cancel')) return
        window.alert('Sharing is not supported on this device/browser.')
      }
    }
  } catch (error) {
    console.error('PDF error', error)
    if (action === 'download') doc.save(fileName)
  }
}
